/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package letscode;

public class App {

    public static void main(String[] args) {

        System.out.println("olá");
        ContaBancaria jeff = new ContaBancaria("$1", "001", "0101", "01001-01");

        System.out.println(jeff.getId());

        ReadFile arquivo = new ReadFile("C:\\Users\\Notebook-2\\Desktop\\projeto_estrutura_dados", "testeFile", "csv");
        arquivo.openFile();
//        System.out.println(arquivo);


    }
}
